"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, AudioLines, FileCheck2, FileText, Image as ImageIcon, Search, ShieldCheck, Video, X } from "lucide-react";
import AppShell from "@/components/AppShell";
import { scamCategories, scamPlatforms, scamReports, scamRisks, scamStatuses, platformActivity, trendData } from "@/services/scamData";

const detectorActions = [["Image", "/upload/image", ImageIcon], ["Document", "/upload/document", FileCheck2], ["Audio", "/upload/audio", AudioLines], ["Video", "/upload/video", Video], ["Text", "/upload/text", FileText]];

function ReportForm({ onClose }) {
  const [form, setForm] = useState({ platform: "", category: "", description: "", link: "", date: "", details: "" });
  const [saved, setSaved] = useState(false);
  const submit = (event) => { event.preventDefault(); const reports = JSON.parse(localStorage.getItem("deepshield-user-reports") || "[]"); localStorage.setItem("deepshield-user-reports", JSON.stringify([{ ...form, id: Date.now(), sourceType: "user-report" }, ...reports])); setSaved(true); };
  if (saved) return <div className="report-success"><ShieldCheck size={24} /><h2>Report saved locally</h2><p>Thank you. This prototype stores your report in this browser and does not treat it as verified intelligence.</p><button className="report-button" onClick={onClose}>Close</button></div>;
  return <form onSubmit={submit} className="report-form"><div className="report-form-heading"><div><p className="page-kicker">User report</p><h2>Report a scam</h2></div><button type="button" onClick={onClose} aria-label="Close report form"><X size={18} /></button></div><div className="report-fields"><label>Platform<input required value={form.platform} onChange={(e) => setForm({ ...form, platform: e.target.value })} placeholder="WhatsApp, email, phone..." /></label><label>Category<input required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="Phishing, investment..." /></label><label className="report-wide">Description<textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Suspicious link<input value={form.link} onChange={(e) => setForm({ ...form, link: e.target.value })} placeholder="Optional" /></label><label>Date<input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label className="report-wide">Additional details<textarea value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} /></label></div><button className="report-button">Save user report</button></form>;
}

export default function ScamDashboard() {
  const [query, setQuery] = useState("");
  const [filters, setFilters] = useState({ platform: "All", category: "All", risk: "All", status: "All" });
  const [showReport, setShowReport] = useState(false);
  const filteredScams = useMemo(() => scamReports.filter((scam) => `${scam.title} ${scam.category} ${scam.platforms.join(" ")} ${scam.description}`.toLowerCase().includes(query.toLowerCase())).filter((scam) => filters.platform === "All" || scam.platforms.includes(filters.platform)).filter((scam) => filters.category === "All" || scam.category === filters.category).filter((scam) => filters.risk === "All" || scam.risk === filters.risk).filter((scam) => filters.status === "All" || scam.status === filters.status), [filters, query]);
  const emerging = scamReports.filter((scam) => scam.status === "New");
  const highRisk = scamReports.filter((scam) => ["High", "Critical"].includes(scam.risk)).length;

  return <AppShell><div className="page-frame intelligence-page">
    <section className="intel-hero reveal"><div><p className="page-kicker">Scam intelligence / demo dataset</p><h1 className="page-title">Know the threat before<br /><em>you become the target.</em></h1><p className="page-subtitle">Explore emerging scams, common fraud patterns and the platforms where they are spreading.</p></div><div className="intel-status"><span className="status-dot" /><b>DEMO INTELLIGENCE</b><small>Demonstration data · not live monitoring</small></div></section>
    <section className="intel-summary reveal reveal-delay"><div><span>DEMO / NEW SCAMS</span><strong>{emerging.length}</strong></div><div><span>ACTIVE THREATS</span><strong>{scamReports.filter((s) => s.status === "Active").length}</strong></div><div><span>PLATFORMS</span><strong>{new Set(scamReports.flatMap((s) => s.platforms)).size}</strong></div><div><span>HIGH RISK</span><strong>{highRisk}</strong></div></section>
    <section className="intel-search reveal reveal-delay-2"><div className="intel-search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search scams..." /></div><button className="report-button" onClick={() => setShowReport(true)}>Report a Scam</button></section>
    <section className="intel-filters reveal"><select aria-label="Filter by platform" value={filters.platform} onChange={(e) => setFilters({ ...filters, platform: e.target.value })}>{scamPlatforms.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by category" value={filters.category} onChange={(e) => setFilters({ ...filters, category: e.target.value })}>{scamCategories.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by risk" value={filters.risk} onChange={(e) => setFilters({ ...filters, risk: e.target.value })}>{scamRisks.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter by status" value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}>{scamStatuses.map((value) => <option key={value}>{value}</option>)}</select>{(query || Object.values(filters).some((value) => value !== "All")) && <button type="button" className="clear-intel-filters" onClick={() => { setQuery(""); setFilters({ platform: "All", category: "All", risk: "All", status: "All" }); }}>Clear filters</button>}</section>
    <section className="intel-main-grid"><div id="recent-scams"><div className="intel-section-heading"><div><p className="eyebrow-rule">What is happening</p><h2>Recent Scam Activity</h2></div><span>{filteredScams.length} demo reports</span></div><div className="scam-list">{filteredScams.map((scam) => <Link href={`/scams/${scam.id}`} className="scam-row" key={scam.id}><div className="scam-row-title"><span className={`scam-status-dot status-${scam.status.toLowerCase()}`} /><div><h3>{scam.title}</h3><p>{scam.description}</p></div></div><span className="scam-category">{scam.category}</span><span className="scam-platforms">{scam.platforms.join(" · ")}</span><span className={`scam-risk risk-${scam.risk.toLowerCase()}`}>{scam.risk}</span><ArrowRight size={16} /></Link>)}{!filteredScams.length && <div className="intel-empty">No scam reports match these filters.</div>}</div></div><aside id="emerging-scams"><div className="emerging-panel surface"><div className="intel-section-heading"><div><p className="eyebrow-rule">Watch closely</p><h2>New & Emerging</h2></div></div>{emerging.map((scam) => <Link href={`/scams/${scam.id}`} className="emerging-row" key={scam.id}><span>NEW</span><div><strong>{scam.title}</strong><small>{scam.platforms.join(" · ")} · {scam.category} · First observed {scam.firstObserved}</small></div></Link>)}</div><div className="safety-callout"><p className="page-kicker">Stay safe</p><h2>Pause. Verify. Then respond.</h2><p><AlertTriangle size={15} /> Never share OTPs or passwords.</p><p><AlertTriangle size={15} /> Verify unexpected payment requests.</p><p><AlertTriangle size={15} /> Check links before opening them.</p></div></aside></section>
    <section className="known-patterns" id="known-patterns"><div className="intel-section-heading"><div><p className="eyebrow-rule">Established patterns</p><h2>Known Scam Patterns</h2></div><span>Warning signs at a glance</span></div><div className="known-grid">{scamReports.filter((scam) => scam.status === "Known").map((scam) => <Link href={`/scams/${scam.id}`} className="known-item" key={scam.id}><span>{scam.category}</span><strong>{scam.title}</strong><p><b>Looks like:</b> {scam.description}</p><p><b>Watch for:</b> {scam.warningSigns[0]}</p><small>View details <ArrowRight size={13} /></small></Link>)}</div></section>
    <section className="platform-section"><div className="intel-section-heading"><div><p className="eyebrow-rule">Where patterns appear</p><h2>Platform Intelligence</h2></div><span>Demo data · not real-time</span></div><div className="platform-grid">{platformActivity.map((item) => <div className="platform-row" key={item.platform}><div><strong>{item.platform}</strong><small>{item.category}</small></div><div className="activity-bar"><span style={{ width: `${Math.min(item.count * 10, 100)}%` }} /></div><span className={`activity-level level-${item.activity.toLowerCase()}`}>{item.activity}</span></div>)}</div></section>
    <section className="trend-section" id="scam-trends"><div className="intel-section-heading"><div><p className="eyebrow-rule">Pattern movement</p><h2>Trending Scam Categories</h2></div><span>Demo data</span></div><div className="trend-grid">{trendData.map((trend) => <div className={`trend-item trend-${trend.direction}`} key={trend.category}><span>{trend.marker}</span><strong>{trend.category}</strong><small>{trend.direction}</small></div>)}</div></section>
    <section className="verify-strip"><div><p className="page-kicker">Suspicious content?</p><h2>Verify something before you trust it.</h2><p>Use the right DeepShield instrument for a closer look.</p></div><div className="verify-actions">{detectorActions.map(([label, href, Icon]) => <Link href={href} key={href}><Icon size={17} />{label}</Link>)}</div></section>
    {showReport && <div className="report-overlay"><div className="report-modal surface"><ReportForm onClose={() => setShowReport(false)} /></div></div>}
  </div></AppShell>;
}
