export const scamCategories = ["All", "Phishing", "UPI Fraud", "Investment Scam", "Job Scam", "Delivery Scam", "Banking Scam", "Impersonation", "AI Voice Scam"];
export const scamPlatforms = ["All", "WhatsApp", "Instagram", "Telegram", "Email", "SMS", "Websites", "Phone Calls", "UPI"];
export const scamRisks = ["All", "Low", "Medium", "High", "Critical"];
export const scamStatuses = ["All", "New", "Active", "Known", "Resolved"];

export const scamReports = [
  { id: "kyc-refresh", title: "Fake Bank KYC Refresh", category: "Banking Scam", platforms: ["SMS", "WhatsApp"], description: "Urgent messages claim your account will be blocked unless you complete a KYC link.", risk: "High", status: "Active", firstObserved: "2026-09-05", lastUpdated: "2026-09-12", warningSigns: ["Urgent account-blocking language", "Shortened or unfamiliar links", "Requests for OTP or card details"], howItWorks: "A message impersonates a bank and sends the target to a lookalike form designed to collect credentials.", sourceType: "demo", detector: "/upload/text" },
  { id: "parcel-refund", title: "Parcel Delivery Refund", category: "Delivery Scam", platforms: ["WhatsApp", "SMS"], description: "A failed-delivery notice asks for a small fee or payment confirmation to reschedule a parcel.", risk: "Medium", status: "Known", firstObserved: "2026-08-21", lastUpdated: "2026-09-10", warningSigns: ["Unexpected delivery notice", "Tiny payment request", "Pressure to act immediately"], howItWorks: "The sender uses a delivery brand and a small fee to push a payment link or collect request.", sourceType: "demo", detector: "/upload/text" },
  { id: "voice-cfo", title: "AI Voice Executive Impersonation", category: "AI Voice Scam", platforms: ["Phone Calls", "WhatsApp"], description: "A familiar-sounding voice asks an employee to urgently transfer funds or share a code.", risk: "Critical", status: "New", firstObserved: "2026-09-11", lastUpdated: "2026-09-14", warningSigns: ["Unusual urgency", "Request to bypass normal approval", "Caller avoids independent verification"], howItWorks: "Voice synthesis is used to imitate a trusted person and create pressure during a short call.", sourceType: "demo", detector: "/upload/audio" },
  { id: "trading-group", title: "Private Trading Group", category: "Investment Scam", platforms: ["Telegram", "Instagram"], description: "A private group promises guaranteed returns and asks members to deposit through an unfamiliar platform.", risk: "High", status: "Active", firstObserved: "2026-08-14", lastUpdated: "2026-09-09", warningSigns: ["Guaranteed returns", "Screenshots instead of statements", "Withdrawal fees or extra deposits"], howItWorks: "Social proof and fabricated profits are used to build trust before the target is asked for larger deposits.", sourceType: "demo", detector: "/upload/document" },
  { id: "remote-job", title: "Remote Job Registration Fee", category: "Job Scam", platforms: ["Instagram", "Websites"], description: "A polished job listing requests a registration, training, or equipment fee before an interview.", risk: "Medium", status: "Known", firstObserved: "2026-07-30", lastUpdated: "2026-09-06", warningSigns: ["Fee before employment", "Unverifiable recruiter", "Non-company email address"], howItWorks: "A fake hiring workflow collects identity documents or fees while promising a role that does not exist.", sourceType: "demo", detector: "/upload/document" },
  { id: "support-account", title: "Fake Customer Support Account", category: "Impersonation", platforms: ["X", "Instagram", "WhatsApp"], description: "A lookalike support profile offers help and asks for remote access, OTPs, or a payment confirmation.", risk: "High", status: "Active", firstObserved: "2026-08-03", lastUpdated: "2026-09-08", warningSigns: ["Unsolicited support outreach", "Requests for remote access", "Profile has subtle spelling differences"], howItWorks: "Impersonators monitor public complaints and contact users first, presenting a fake resolution path.", sourceType: "demo", detector: "/upload/image" },
  { id: "upi-collect", title: "UPI Collect Request", category: "UPI Fraud", platforms: ["UPI", "WhatsApp"], description: "A sender says a payment is waiting and asks the target to approve a collect request or scan a code.", risk: "Critical", status: "Known", firstObserved: "2026-07-18", lastUpdated: "2026-09-04", warningSigns: ["Receiving money requires a PIN", "Unexpected collect request", "QR code presented as a refund"], howItWorks: "The target is persuaded to approve a debit while believing they are receiving money.", sourceType: "demo", detector: "/upload/image" },
  { id: "prize-link", title: "Lottery Prize Link", category: "Phishing", platforms: ["Email", "SMS"], description: "A prize notification links to a form requesting personal data, fees, or payment details.", risk: "Low", status: "Resolved", firstObserved: "2026-06-10", lastUpdated: "2026-08-30", warningSigns: ["Prize you did not enter", "Generic sender address", "Processing fee request"], howItWorks: "The promise of a reward gets the target to open a link and volunteer sensitive information.", sourceType: "demo", detector: "/upload/text" },
].map((scam) => ({
  ...scam,
  recommendedAction: "Pause, verify through an official channel, and avoid sharing credentials or sending money.",
}));

export const platformActivity = [
  ["WhatsApp", 8, "High", "Impersonation"], ["Instagram", 6, "Moderate", "Job Scam"], ["Telegram", 5, "High", "Investment Scam"], ["Email", 4, "Moderate", "Phishing"], ["SMS", 7, "High", "Banking Scam"], ["Websites", 3, "Moderate", "Job Scam"], ["Phone Calls", 4, "High", "AI Voice Scam"], ["UPI", 5, "Critical", "UPI Fraud"],
].map(([platform, count, activity, category]) => ({ platform, count, activity, category }));

export const trendData = [
  ["AI Voice Impersonation", "increasing", "↑"], ["Investment Scams", "increasing", "↑"], ["Fake Delivery Messages", "stable", "→"], ["Phishing", "stable", "→"], ["Lottery Scams", "decreasing", "↓"],
].map(([category, direction, marker]) => ({ category, direction, marker }));
