import os
from pypdf import PdfReader
from docx import Document

def extract_document_text(file_path):
    """
    Extract text from PDF, DOCX and TXT files.
    """

    extension = os.path.splitext(file_path)[1].lower()

    try:

        # -------------------------
        # PDF
        # -------------------------
        if extension == ".pdf":

            reader = PdfReader(file_path)

            text = ""

            for page in reader.pages:
                page_text = page.extract_text()

                if page_text:
                    text += page_text + "\n"

            return text.strip()


        # -------------------------
        # DOCX
        # -------------------------
        elif extension == ".docx":

            document = Document(file_path)

            text = ""

            for paragraph in document.paragraphs:
                text += paragraph.text + "\n"

            return text.strip()


        # -------------------------
        # TXT
        # -------------------------
        elif extension == ".txt":

            with open(
                file_path,
                "r",
                encoding="utf-8",
                errors="ignore"
            ) as file:

                return file.read().strip()


        # -------------------------
        # Unsupported
        # -------------------------
        else:

            return "Unsupported document format."

    except Exception as e:

        return f"Document extraction error: {str(e)}"


def analyze_document(file_path):

    text = extract_document_text(file_path)

    word_count = len(text.split())

    character_count = len(text)

    # Basic suspicious-document indicators
    suspicious_keywords = [
        "generated by ai",
        "chatgpt",
        "artificial intelligence",
        "deepfake",
        "generated content",
        "ai generated"
    ]

    lower_text = text.lower()

    detected_keywords = [
        keyword
        for keyword in suspicious_keywords
        if keyword in lower_text
    ]

    if detected_keywords:

        ai_probability = min(
            30 + len(detected_keywords) * 15,
            90
        )

    else:

        ai_probability = 10


    return {
        "text": text,
        "word_count": word_count,
        "character_count": character_count,
        "ai_probability": ai_probability,
        "suspicious_keywords": detected_keywords
    }