import re


SUSPICIOUS_PATTERNS = {
    "ai_disclosure": [
        "generated by ai",
        "written by chatgpt",
        "created by artificial intelligence",
        "ai-generated",
    ],
    "generic_ai_phrasing": [
        "in conclusion",
        "it is important to note",
        "delve into",
        "plays a crucial role",
    ],
}


def analyze_text(text):
    """Return a lightweight heuristic result, not proof of AI authorship."""
    normalized_text = text.strip()
    lower_text = normalized_text.lower()
    words = re.findall(r"\b\w+[\w'-]*\b", normalized_text)
    indicators = []

    for indicator_type, patterns in SUSPICIOUS_PATTERNS.items():
        for pattern in patterns:
            if pattern in lower_text:
                indicators.append({"type": indicator_type, "pattern": pattern})

    sentences = [
        sentence.strip()
        for sentence in re.split(r"[.!?]+", normalized_text)
        if sentence.strip()
    ]
    sentence_starts = [
        sentence.split()[0].lower()
        for sentence in sentences
        if sentence.split()
    ]
    repeated_starts = {
        start for start in sentence_starts if sentence_starts.count(start) >= 3
    }

    if repeated_starts:
        indicators.append({
            "type": "repeated_sentence_starts",
            "pattern": ", ".join(sorted(repeated_starts)),
        })

    ai_probability = min(len(indicators) * 15, 60)
    risk = "Medium" if ai_probability >= 45 else "Low"

    return {
        "label": "Prototype Text Analysis",
        "ai_probability": ai_probability,
        "risk": risk,
        "word_count": len(words),
        "character_count": len(normalized_text),
        "suspicious_patterns": indicators,
    }
